<?php
require 'php/getCharacter.php';
?>


<div class="row">
    <div id="character" class="container-fluid">



        <div class="row d-flex justify-content-center">
            <?php include "header.phtml" ?>
            <div id="statsChar " class="col-lg-3 col-md-8 col-sm-8 m-2 box">
                <h2>Stats</h2>
                <div class="statsItem">
                    <h3>Niveau : <span>
                            <?php echo $character->level ?></span></h3>
                </div>
                <div class="statsItem">
                    <h3 id="life" data-stats="<?php echo $character->vie ?>">Vie : <span id="persoVie">
                            <?php echo  $character->vie ?></span></h3>
                </div>
                <div class="statsItem">
                    <h3 id="attack" data-stats="<?php echo $character->attaque ?>">Attaque : <span id="persoAtt">
                            <?php echo $character->attaque ?></span></h3>
                </div>
                <div class="statsItem">
                    <h3 id="defense" data-stats="<?php echo $character->defense ?>">Défense : <span id="persoDef">
                            <?php echo $character->defense ?></span></h3>
                </div>
                <div class="statsItem">
                    <h3 id="critic" data-stats="<?php echo $character->critique ?>">Critique : <span id="persoCrit">
                            <?php echo  $character->critique ?>%</span></h3>
                </div>
            </div>

            <div id="vueChar" class="col-lg-5 col-md-8 col-sm-8 m-2 box" align="center ">
                <h2>
                    <?php echo $user->username ?>
                </h2>
                <div class="row d-flex justify-content-center">
                    <div id="helmet" class="col-lg-2 characterCell characterHead"></div>
                </div>
                <div class="row d-flex justify-content-center">
                    <div id="sword" class="col-lg-2 characterCell m-2 characterLeftArm"></div>
                    <div id="armour" class="col-lg-2 characterCell m-2 characterBody"></div>
                    <div id="shield" class="col-lg-2 characterCell m-2 characterRightArm"></div>
                </div>
                <div class="row d-flex justify-content-center">
                    <div id="boots" class="col-lg-2 characterCell m-2 characterLeg"></div>
                </div>
            </div>

            <div id="inventory" class="col-lg-3 col-md-8 col-sm-8 m-2 box">
                <h2>Inventaire</h2>
                <div class="row d-flex justify-content-center">
                    <?php foreach ($detailsInv as $i){ ?>
                    <div class="col-lg-3 itemCell m-1" data-item="<?php echo $i->type_equipement ?>" data-level="<?php echo $i->level_min ?>" data-attaque="<?php echo $i->attaque ?>" data-defense="<?php echo $i->defense ?>" data-critique="<?php echo $i->critique ?>" data-vie="<?php echo $i->vie ?>">
                        <img class="itemImg" src="img/<?php echo  $i->img ?>">
                        <div id="overlay<?php echo  $cmpt ?>" class="overlay">
                            <div>
                                <h3>
                                    <?php echo  $i->nom_equipement ?>
                                </h3>
                            </div>
                            <div>
                                <div>
                                    <h3>Level : <span>
                                            <?php echo  $i->level_min ?></span></h3>
                                </div>
                                <div>
                                    <h3>Attaque : <span>
                                        <?php echo  $i->attaque ?></span></h3>
                                </div>
                                <div>
                                    <h3>Defense : <span>
                                            <?php echo  $i->defense ?></span></h3>
                                </div>
                                <div>
                                    <h3>Critique : <span>
                                        <?php echo  $i->critique ?></span></h3>
                                </div>
                                <div>
                                    <h3>Vie : <span>
                                        <?php echo  $i->vie ?></span></h3>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php $cmpt += 1; } ?>
                </div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    var character = <?php echo json_encode($character, JSON_FORCE_OBJECT) ?>

    function showOverlay() {
        $(".itemCell").hover(function() {
            $(this).children().show();
        });
        $(".itemCell").mouseleave(function() {
            $(this).children(".overlay").hide();
        });
    }

    function addItem() {
        
        
        $(".itemCell").click(function() {
            var item = $(this);
            var itemType = $(this).data("item");
            var att = $(this).data("attaque");
            var def = $(this).data("defense");
            var crit = $(this).data("critique");
            var lvl = $(this).data("level");
            var vie = $(this).data("vie");
            if (itemType == 0 && lvl <= character.level) {
                var charItem = $("#sword").children(".itemCell");
                console.log(charItem)
                $("#inventory").find(".row").append(charItem);
                $("#sword").append(item);
                $('#persoAtt').text((parseInt(character.attaque)+parseInt(att)).toString());
                $('#persoDef').text((parseInt(character.defense)+parseInt(def)).toString());
                $('#persoCrit').text((parseInt(character.critique)+parseInt(crit)).toString() + "%");
                $('#persoVie').text((parseInt(character.vie)+parseInt(vie)).toString());
                character.attaque = parseInt(character.attaque)+parseInt(att);
                character.defense = parseInt(character.defense)+parseInt(def);
                character.critique = parseInt(character.critique)+parseInt(crit);
                character.vie = parseInt(character.vie)+parseInt(vie);
            }
            if (itemType == 1 && lvl <= character.level) {
                var charItem = $("#helmet").children(".itemCell");
                $("#inventory").find(".row").append(charItem);
                $("#helmet").append(item);
                $('#persoAtt').text((parseInt(character.attaque)+parseInt(att)).toString());
                $('#persoDef').text((parseInt(character.defense)+parseInt(def)).toString());
                $('#persoCrit').text((parseInt(character.critique)+parseInt(crit)).toString() + "%");
                $('#persoVie').text((parseInt(character.vie)+parseInt(vie)).toString());
                character.attaque = parseInt(character.attaque)+parseInt(att);
                character.defense = parseInt(character.defense)+parseInt(def);
                character.critique = parseInt(character.critique)+parseInt(crit);
                character.vie = parseInt(character.vie)+parseInt(vie);
            }
            if (itemType == 2 && lvl <= character.level) {
                var charItem = $("#armour").children(".itemCell");
                $("#inventory").find(".row").append(charItem);
                $("#armour").append(item);
                $('#persoAtt').text((parseInt(character.attaque)+parseInt(att)).toString());
                $('#persoDef').text((parseInt(character.defense)+parseInt(def)).toString());
                $('#persoCrit').text((parseInt(character.critique)+parseInt(crit)).toString() + "%");
                $('#persoVie').text((parseInt(character.vie)+parseInt(vie)).toString());
                character.attaque = parseInt(character.attaque)+parseInt(att);
                character.defense = parseInt(character.defense)+parseInt(def);
                character.critique = parseInt(character.critique)+parseInt(crit);
                character.vie = parseInt(character.vie)+parseInt(vie);
            }
            if (itemType == 3 && lvl <= character.level) {
                var charItem = $("#boots").children(".itemCell");
                $("#inventory").find(".row").append(charItem);
                $("#boots").append(item);
                $('#persoAtt').text((parseInt(character.attaque)+parseInt(att)).toString());
                $('#persoDef').text((parseInt(character.defense)+parseInt(def)).toString());
                $('#persoCrit').text((parseInt(character.critique)+parseInt(crit)).toString() + "%");
                $('#persoVie').text((parseInt(character.vie)+parseInt(vie)).toString());
                character.attaque = parseInt(character.attaque)+parseInt(att);
                character.defense = parseInt(character.defense)+parseInt(def);
                character.critique = parseInt(character.critique)+parseInt(crit);
                character.vie = parseInt(character.vie)+parseInt(vie);
            }
            if (itemType == 4 && lvl <= character.level) {
                var charItem = $("#shield").children(".itemCell");
                $("#inventory").find(".row").append(charItem);
                $("#shield").append(item);
                $('#persoAtt').text((parseInt(character.attaque)+parseInt(att)).toString());
                $('#persoDef').text((parseInt(character.defense)+parseInt(def)).toString());
                $('#persoCrit').text((parseInt(character.critique)+parseInt(crit)).toString() + "%");
                $('#persoVie').text((parseInt(character.vie)+parseInt(vie)).toString());
                character.attaque = parseInt(character.attaque)+parseInt(att);
                character.defense = parseInt(character.defense)+parseInt(def);
                character.critique = parseInt(character.critique)+parseInt(crit);
                character.vie = parseInt(character.vie)+parseInt(vie);
            }
            //console.log(character); 
        });
    }
    function removeItem(){
        $(".characterCell").click(function(){
            console.log("click");
            var item = $(this).children(".itemCell");
            console.log(item);
            $("#inventory").find(".row").append(item);
        })
    }
    removeItem();
    addItem();
    showOverlay();  
</script>