<?php
require 'php/getCharacter.php';
?>


<div class="row">
    <div id="character" class="container-fluid">



        <div class="row d-flex justify-content-center">
            <div id="menu">
                <h1 class="logo">MiniBoys</h1>
                <a href="Co.php" class=" btn-default btn disabled">Personnage</a>
                <a href="Co.php?cmpgn=yes" class=" btn-default btn ">Campagne</a>
                <a href="php/delete.php" class=" btn-default btn off ">Deconnexion</a>
            </div>
            <div id="statsChar " class="col-lg-3 col-md-8 col-sm-8 m-2 box">
                <h2>Stats</h2>
                   <div class="statsItem">
                        <h3>Niveau : <span> <?php echo $character->level ?></span></h3>
                    </div>
                    <div class="statsItem">
                        <h3>Vie : <span> <?php echo  $character->vie ?></span></h3>
                    </div>
                    <div class="statsItem">
                        <h3>Attaque : <span> <?php echo $character->attaque ?></span></h3>
                    </div>
                    <div class="statsItem">
                        <h3>Défense : <span> <?php echo $character->defense ?></span></h3>
                    </div>
                    <div class="statsItem">
                        <h3>Critique : <span> <?php echo  $character->critique ?>%</span></h3>
                    </div>
            </div>

            <div id="vueChar" class="col-lg-5 col-md-8 col-sm-8 m-2 box" align="center ">
                <h2>
                    <?php echo $user->username ?>
                </h2>
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-2 characterCell characterHead"></div>
                </div>
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-2 characterCell m-2 characterLeftArm"></div>
                    <div class="col-lg-2 characterCell m-2 characterBody"></div>
                    <div class="col-lg-2 characterCell m-2 characterRightArm"></div>
                </div>
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-2 characterCell m-2 characterLeg"></div>
                </div>
            </div>

            <div id="inventory" class="col-lg-3 col-md-8 col-sm-8 m-2 box">
                <h2>Inventaire</h2>
                <div class="row d-flex justify-content-center">
                    <?php foreach ($detailsInv as $i){ ?>
                    <div id="itemCell<?php echo  $cmpt ?>" class="col-lg-3 itemCell m-1"> </div>
                    <div id="overlay<?php echo  $cmpt ?>" class="overlay">
                        <h5><?php echo  $i->nom_equipement ?></h5>
                        <table>
                            <tr>
                                <td>Level :</td>
                                <td><?php echo  $i->level_min ?></td>
                            </tr>
                            <tr>
                                <td>Attaque :</td>
                                <td><?php echo  $i->attaque ?></td>
                            </tr>
                            <tr>
                                <td>Defense :</td>
                                <td><?php echo  $i->defense ?></td>
                            </tr>
                            <tr>
                                <td>Critique :</td>
                                <td><?php echo  $i->critique ?></td>
                            </tr>
                            <tr>
                                <td>Vie :</td>
                                <td><?php echo  $i->vie ?></td>
                            </tr>
                        </table>
                    </div>
                    <?php $cmpt += 1; } ?>
                </div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function showOverlay(index) {
        document.getElementById("overlay"+index).style.display = "block";
    }
</script>