<?php
require 'php/game.php';
/*var_dump($character);
var_dump($manche);
var_dump($ennemi);
var_dump($equipement);*/
?>
<script>
    class Personnage {
        constructor(span_vie, name, vie, attaque, defense, critique) {
            this.name = name;
            this.vie_max = vie;
            this.current_vie = vie;
            this.attaque = attaque;
            this.defense = defense;
            this.critique = critique;
            this.span_vie = span_vie;
        }

        goAttaque(cible, multiplicateur, txt) {
            console.log('attaque');
            var mult_critique = 1;
            var random_crit = getRandomInt(100) + 1;
            if (random_crit <= this.critique) {
                txt.innerHTML += this.name + " a fait un coup critique !</br>"
                mult_critique = 2;
            }
            var nb_dommage = this.attaque * multiplicateur * mult_critique - cible.defense;
            if (nb_dommage < 0) {
                nb_dommage = 0;
            }
            txt.innerHTML += this.name + " a fait une attaque de " + nb_dommage + " dégats.</br>";
            var rslt = cible.isAttaque(nb_dommage, txt);
            return rslt;
        }

        isAttaque(nb_dommage, txt) {
            this.current_vie -= nb_dommage;
            var rslt = true;
            if (this.current_vie <= 0) {
                this.current_vie = 0;
                txt.innerHTML += this.name + " est mort!</br>";
                rslt = false;
            }
            this.refreshLife();
            return rslt;
        }
        refreshLife() {
            var span_vie = document.getElementById(this.span_vie);
            span_vie.innerHTML = this.current_vie;
        }
    }
    var perso = new Personnage("vie_joueur", "<?php echo $user->username ; ?>", <?php echo $character->vie ; ?>, <?php echo $character->attaque ; ?>, <?php echo $character->defense ; ?>, <?php echo $character->critique; ?>);
    var ennemi = new Personnage("vie_ennemi", "<?php echo $ennemi->nom ; ?>", <?php echo $ennemi->vie ; ?>, <?php echo $ennemi->attaque ; ?>, <?php echo $ennemi->defense ; ?>, <?php echo $ennemi->critique; ?>);
    console.log(perso);
    console.log(ennemi);

    function getRandomInt(max) {
        return Math.floor(Math.random() * Math.floor(max));
    }

    function endGame(end_game) {
        var id_campagne = <?php echo $manche->id_campagne?>;
        window.location.replace('Co.php?page=endgame&end_game=' + end_game + "&id_campagne=" + id_campagne);
    }

    function bataille(type_j) {
        if( $("#playerCharacter").hasClass("knightAttack")){
            $(this).removeClass("knightAttack");
        }
       if( $("#playerCharacter").hasClass("apply-shake")){
            $(this).removeClass("apply-shake");
        }
        $("#enemyCharacter").removeClass("apply-shake");
        $("#playerCharacter").removeClass("apply-shake");
        $("#playerCharacter").removeClass("knightAttack");
        var type = ['pierre', 'feuille', 'ciseaux'];
        var type_e = getRandomInt(3);
        var div_txt = document.getElementById("txt_bataille");
        div_txt.innerHTML += "Vous avez fait " + type[type_j] + "</br>";
        div_txt.innerHTML += "Votre ennemi a fait " + type[type_e] + "</br>";
        $("#playerAttack").attr("src", "img/" + type[type_j] + ".png");
        $("#enemiAttack").attr("src", "img/" + type[type_e] + ".png");

        var rslt;
        if (type_e == type_j) {
            rslt = 0;
            div_txt.innerHTML += "Egaliter !</br>";

            $("#playerCharacter").addClass("apply-shake");
            $("#enemyCharacter").addClass("apply-shake");
            if (perso.goAttaque(ennemi, 1, div_txt) == false) {
                endGame(1);
            }
            if (ennemi.goAttaque(perso, 1, div_txt) == false) {
                endGame(0);
            }
        } else if ((type_e + 1) % 3 == type_j) {
            rslt = 1;
            div_txt.innerHTML += "Vous avez gagné !</br>";
            $("#playerCharacter").addClass("knightAttack");
            $("#enemyCharacter").addClass("apply-shake");

            if (perso.goAttaque(ennemi, 1, div_txt) == false) {
                endGame(1);
            }
        } else {
            rslt = 2;
            div_txt.innerHTML += "Vous avez perdu !</br>";
            $("#playerCharacter").addClass("apply-shake");

            if (ennemi.goAttaque(perso, 1, div_txt) == false) {
                endGame(0);
            }
        }

    }
</script>
<div class="row">
   <div id="cutSound"></div>
    <section class="rain"></section>
    <div id="game" class="container-fluid">
        <?php include "header.phtml"; ?>
        <div id="stageLvl">Stage :  <?php echo $niveau_manche ?></div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-3 m-2 platform leftPlatform">
                <div class="lifeContainer">
                    <div class="lifeBar playerLifeBar">
                        <div class="lifePoint "><span id="vie_joueur">
                                <?php echo $character->vie ?> </span>/
                            <?php echo $character->vie ?>
                        </div>
                    </div>
                </div>
                <!--
                <img id="playerCharacter" class="battleCharacter" src="/MiniBoys/img/guerrier.png" alt="">
-->
                <div id="playerCharacter" class="knight"><div class="knightHeal"></div></div>
                <img class="platformImg" src="/MiniBoys/img/platformGreen.png" alt="">
                <div class="row d-flex justify-content-center align-items-center inGameStatsContainer">
                    <div class="col-4 inGameStats">Lvl :
                        <?php echo $character->level ?>
                    </div>
                    <div class="col-4 inGameStats">Attaque :
                        <?php echo $character->attaque ?>
                    </div>
                    <div class="col-4 inGameStats">Défense :
                        <?php echo $character->defense ?>
                    </div>
                </div>
            </div>
            <div class="col-lg-2  m-2 vs d-flex justify-content-center align-items-center">
                <div class="attack">
                    <img id="playerAttack" class="img-fluid" src="" alt="">
                </div>
                <div class="attack vsIcon">
                    <img class="img-fluid" src="img/vs.png" alt="">
                </div>
                <div class="attack">
                    <img id="enemiAttack" class="img-fluid" src="" alt="">
                </div>
            </div>
            <div class="col-lg-3 m-2 platform rightPlatfrom">
                <div class="lifeContainer">
                    <div class="lifeBar enemiLifeBar">
                        <div class="lifePoint"> <span id="vie_ennemi">
                                <?php echo $ennemi->vie ?> </span>/
                            <?php echo $ennemi->vie ?>
                        </div>
                    </div>
                </div>
                <img id="enemyCharacter" class="battleCharacter" src="/MiniBoys/img/spider2.png" alt="">
                <img class="platformImg" src="/MiniBoys/img/platformGreen.png" alt="">
                <div class="row d-flex justify-content-center align-items-center inGameStatsContainer">

                    <div class="col-6 inGameStats">Attaque :
                        <?php echo $ennemi->attaque ?>
                    </div>
                    <div class="col-6 inGameStats">Défense :
                        <?php echo $ennemi->defense ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="row fixed-bottom txtBattleContainer">

            <div class="battleBtnContainer row d-flex justify-content-center">
                <button id="rock" class="battleBtn" onclick="bataille(0);"></button>
                <button id="leaf" class="battleBtn" onclick="bataille(1);"></button>
                <button id="scissor" class="battleBtn" onclick="bataille(2);"></button>
            </div>
            <div id='txt_bataille'>

            </div>
        </div>
    </div>

</div>
<audio id="my_audio" src="sound/battle.mp3" autoplay="true"></audio>
<script type="text/javascript">
    $(document).ready(function() {
        $("#my_audio").get(0).play();
        $("#cutSound").click(function(){
            $("#my_audio").get(0).pause();
        })
    });

    function autoScrollOnclickBtn() {
        $(".battleBtn").click(function() {
            var scrollDimension = $("#txt_bataille")[0].scrollHeight;
            console.log(scrollDimension);
            $("#txt_bataille").scrollTop(scrollDimension);
        });
    }

    function animateLifeBar() {
        $(".battleBtn").click(function() {
            $(".playerLifeBar").animate({
                width: perso.current_vie + '%'
            });
            $(".enemiLifeBar").animate({
                width: ennemi.current_vie + '%'
            });
        });
    }
    // number of drops created.
    var nbDrop = 80;

    // function to generate a random number range.
    function randRange(minNum, maxNum) {
        return (Math.floor(Math.random() * (maxNum - minNum + 1)) + minNum);
    }

    // function to generate drops
    function createRain() {

        for (i = 1; i < nbDrop; i++) {
            var dropLeft = randRange(0, 1600);
            var dropTop = randRange(-1000, 1400);

            $('.rain').append('<div class="drop" id="drop' + i + '"></div>');
            $('#drop' + i).css('left', dropLeft);
            $('#drop' + i).css('top', dropTop);
        }

    }
    // Make it rain
    createRain();
    autoScrollOnclickBtn();
    animateLifeBar();
</script>