<?php
require 'php/game.php';
/*var_dump($character);
var_dump($manche);
var_dump($ennemi);
var_dump($equipement);*/
?>
<script>
    class Personnage {
        constructor(span_vie, name, vie, attaque, defense, critique) {
            this.name = name;
            this.vie_max = vie;
            this.current_vie = vie;
            this.attaque = attaque;
            this.defense = defense;
            this.critique = critique;
            this.span_vie = span_vie;
        }

        goAttaque(cible, multiplicateur, txt) {
            console.log('attaque');
            var mult_critique = 1;
            var random_crit = getRandomInt(100) + 1;
            if (random_crit <= this.critique) {
                txt.innerHTML += this.name + " a fait un coup critique !</br>"
                mult_critique = 2;
            }
            var nb_dommage = this.attaque * multiplicateur * mult_critique - cible.defense;
            if (nb_dommage < 0) {
                nb_dommage = 0;
            }
            txt.innerHTML += this.name + " a fait une attaque de " + nb_dommage + " dégats.</br>";
            var rslt = cible.isAttaque(nb_dommage, txt);
            return rslt;
        }

        isAttaque(nb_dommage, txt) {
            this.current_vie -= nb_dommage;
            var rslt = true;
            if (this.current_vie <= 0) {
                this.current_vie = 0;
                txt.innerHTML += this.name + " est mort!</br>";
                rslt = false;
            }
            this.refreshLife();
            return rslt;
        }
        refreshLife() {
            var span_vie = document.getElementById(this.span_vie);
            span_vie.innerHTML = this.current_vie;
        }

    }
    var perso = new Personnage("vie_joueur", "<?php echo $user->username ; ?>", <?php echo $character->vie ; ?>, <?php echo $character->attaque ; ?>, <?php echo $character->defense ; ?>, <?php echo $character->critique; ?>);
    var ennemi = new Personnage("vie_ennemi", "<?php echo $ennemi->nom ; ?>", <?php echo $ennemi->vie ; ?>, <?php echo $ennemi->attaque ; ?>, <?php echo $ennemi->defense ; ?>, <?php echo $ennemi->critique; ?>);
    console.log(perso);
    console.log(ennemi);

    function getRandomInt(max) {
        return Math.floor(Math.random() * Math.floor(max));
    }

    function bataille(type_j) {
        var type = ['pierre', 'feuille', 'ciseau'];
        var type_e = getRandomInt(3);
        var div_txt = document.getElementById("txt_bataille");
        div_txt.innerHTML += "Vous avez fait " + type[type_j] + "</br>";
        div_txt.innerHTML += "Votre ennemi a fait " + type[type_e] + "</br>";
        var rslt;
        if (type_e == type_j) {
            rslt = 0;
            div_txt.innerHTML += "Egaliter !</br>";
            perso.goAttaque(ennemi, 1, div_txt);
            ennemi.goAttaque(perso, 1, div_txt);
        } else if ((type_e + 1) % 3 == type_j) {
            rslt = 1;
            div_txt.innerHTML += "Vous avez gagné !</br>";
            perso.goAttaque(ennemi, 2, div_txt);
        } else {
            rslt = 2;
            div_txt.innerHTML += "Vous avez perdu !</br>";
            ennemi.goAttaque(perso, 2, div_txt);
        }
    }
</script>
<div class="row">
    <div id="game" class="container-fluid">
        <?php include "header.phtml"; ?>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-3 m-2 platform leftPlatform">
                <div class="lifeContainer">
                    <div class="lifeBar">
                        <div class="lifePoint"><span id="vie_joueur">
                                <?php echo $character->vie ?> </span>/
                            <?php echo $character->vie ?>
                        </div>
                    </div>
                </div>
                <img class="battleCharacter" src="/MiniBoys/img/guerrier.png" alt="">
                <img class="platformImg" src="/MiniBoys/img/platformGreen.png" alt="">
            </div>
            <div class="col-lg-2  m-2 vs">
                <img class="img-fluid" src="/MiniBoys/img/vs.png" alt="">
            </div>
            <div class="col-lg-3 m-2 platform rightPlatfrom">
                <div class="lifeContainer">
                    <div class="lifeBar">
                        <div class="lifePoint"> <span id="vie_ennemi">
                                <?php echo $ennemi->vie ?> </span>/
                            <?php echo $ennemi->vie ?>
                        </div>
                    </div>
                </div>
                <img class="battleCharacter" src="/MiniBoys/img/ladybug.png" alt="">
                <img class="platformImg" src="/MiniBoys/img/platformGreen.png" alt="">
            </div>
        </div>
        <div class="row">
            <div id='txt_bataille'>
                <button onclick="bataille(0);">Pierre</button>
                <button onclick="bataille(1);">Feuille</button>
                <button onclick="bataille(2);">Ciseau</button>

            </div>
        </div>
    </div>

</div>