<?php
require 'php/function.php';
?>
<div class="row">
    <h1 class="homeLogo">MiniBoys</h1>
    <div id="home" class="container-fluid">
        <div class="row d-flex justify-content-center">
            <div class="connexionContainer">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#menu1">Connection</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#menu2">Inscription</a>
                    </li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane container fade show active" id="menu1">
                        <h2>Connection</h2>
                        <form method="post">
                            <div class="form-group">
                                <label for="email">Adresse Email ou Pseudo:</label>
                                <input type="text" name="username" class="form-control" id="emailCo">
                            </div>
                            <div class="form-group">
                                <label for="pwd">Mot de passe:</label>
                                <input type="password" name="password" class="form-control" id="pwdCo">
                            </div>
                            <button type="submit" class="btn btn-default">Connexion</button>
                        </form>
                    </div>

                    <div class="tab-pane container fade" id="menu2">
                        <h2>Inscription</h2>
                        <form method="post">
                            <div class="form-group">
                                <label for="pseudo">Pseudo:</label>
                                <input type="text" name="username" class="form-control" id="pseudo">
                            </div>
                            <div class="form-group">
                                <label for="email">Adresse Email:</label>
                                <input type="email" name="email" class="form-control" id="emailInsc">
                            </div>
                            <div class="form-group">
                                <label for="pwd">Mot de passe:</label>
                                <input type="password" name="password" class="form-control" id="pwdInsc">
                            </div>
                            <div class="form-group">
                                <label for="pwd1">Retapez votre mot de passe:</label>
                                <input type="password" name="password_confirm" class="form-control" id="pwd1">
                            </div>
                            <button type="submit" class="btn btn-default">S'incrire</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>